defaults: &defaults
  site:
    name: NewApp
    devname: newapp
    domain: newapp.com
    email:
      contact_form: support@newapp.com
      no_reply: no_reply@newapp.com
      
  security:
    enabled: true
    environments:
      - staging
    login: "admin"
    password: "1234"
    
  meta:
    default_title: Untitled
    default_keywords: <No description>
    default_description: <No keywords>
    
  localization:
    default_locale: en
    default_time_zone: UTC
    
  smtp_mail:
    domain: newapp.com
    user_name: mailer@newapp.com
    password: 
    
  sessions:
    id: newapp
    secret: 0728d2b85ed6fe0e31d9b21bcde21f83b0c06bea14a14cdbff5a2bf5ec53a89e75b47a1c9cdd2c224506d4278323856fb642da6b245b2ee84ef26d51b9a7e0d9
    
  api_keys:
    hoptoad: 3b2019ffdeb1cc9612be42adbc18b0a3
    google_analytics: UA-7154429-1
    
  debugging:
    hoptoad:
      track_404s: false
    sanitize_email: &sanitize_email
      recipients: test@newapp.com
      bcc_recipients: test@newapp.com
      cc_recipients: test@newapp.com
    hirb:
      enabled: true
    rack_bug:
      enabled: true
      password: 
      
  preferences:
    forms:
      error_messages: true
    pagination:
      per_page: 20
      ajax: false
      
development:
  <<: *defaults
  debugging:
    sanitize_email:
      <<: *sanitize_email
    hirb:
      enabled: true
    rack_bug:
      enabled: false
      
test:
  <<: *defaults
  smtp_mail:
    domain: localhost:3000
    user_name: mailer@newapp.com
    password: 
    
production:
  <<: *defaults
  smtp_mail:
    domain: localhost:3000
    user_name: mailer@newapp.com
    password: 