:asset_root: public
:source_files:
  - app/javascripts/application.js
:load_path:
  - app/javascripts
  - app/javascripts/**/*
  - vendor/javascripts
  - vendor/javascripts/**/*
  - vendor/fonts
  - vendor/fonts/**/*